apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuzone-app
  namespace: examen-26
  labels:
    app: chuzone
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chuzone
  template:
    metadata:
      labels:
        app: chuzone
    spec:
      containers:
        - name: app
          image: ${{ secrets.DOCKERHUB_USERNAME }}/chuzone-devops-app:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
