apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chuzone-ingress
  namespace: examen-26
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: chuzone-app.duckdns.org # Replace with your actual DuckDNS domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chuzone-service
                port:
                  number: 80
