apiVersion: v1
kind: Service
metadata:
  name: chuzone-service
  namespace: examen-26
spec:
  type: NodePort # Ingress will handle external access
  selector:
    app: chuzone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
